name: chocotoxic
description: Calcule a toxicidade do chocolate ingerido pelo cachorro.
version: 0.1.2+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  #sqflite: ^1.3.0
  #path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/